version: '3'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:latest
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - ./etc/nginx.d/my-proxy.conf:/etc/nginx/conf.d/my-proxy.conf
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    web:
        image: nginx:latest
        expose:
            - 80
        volumes:
            - ${ROOT_PATH}:/var/www
            - ./etc/nginx.d/nginx-custom.conf:/etc/nginx/conf.d/000-nginx-custom.conf
            - ./etc/nginx.d/nginx-gzip.conf:/etc/nginx/conf.d/000-nginx-gzip.conf
            - ./etc/nginx.d/nginx-log-format.conf:/etc/nginx/conf.d/000-nginx-log-format.conf
            - ./etc/nginx.d/sites.conf:/etc/nginx/conf.d/default.conf
        environment:
            - VIRTUAL_HOST=${DOMAINS}
        links:
            - php
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    php:
        build:
            context: ./etc/docker/php7.4
            dockerfile: Dockerfile
        image: infra/php7.4-fpm:latest
        volumes:
            - ${ROOT_PATH}:/var/www
            - ./etc/php.d/custom.fpm.ini:/usr/local/etc/php-fpm.d/custom.ini
            - ./etc/php.d/custom.php.ini:/usr/local/etc/php/conf.d/custom-php.ini
        links:
            - dbserver
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    dbserver:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - ./etc/mysql.d:/etc/mysql/conf.d
            - ./mysql-initdb.d:/docker-entrypoint-initdb.d
            - type: bind
              source: ./mysql-data
              target: /var/lib/mysql
        logging:
            options:
                max-size: "10m"
                max-file: "3"